<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.shibboleth</groupId>
        <artifactId>parent</artifactId>
        <version>17.2.2</version>
    </parent>

    <name>Shibboleth IdP :: Plugins :: Esup-Otp Login Flow</name>
    <description>An IdP plugin providing Esup-Otp login support.</description>
    <groupId>fr.renater.shibboleth.esup.otp</groupId>
    <artifactId>idp-plugin-esup-otp</artifactId>
    <version>1.1.0</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>

        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <shibboleth.projectName>java-idp-plugin-esup-otp</shibboleth.projectName>

        <idp.groupId>net.shibboleth.idp</idp.groupId>
        <idp.version>5.2.1</idp.version>
        <opensaml.version>5.2.1</opensaml.version>
        <shib-profile.version>5.2.1</shib-profile.version>

        <slf4j.version>2.0.18</slf4j.version>
        <logback.version>1.5.34</logback.version>

        <lombok.version>1.18.46</lombok.version>

        <jcommander>3.0</jcommander>

        <mockito.version>5.23.0</mockito.version>
        <testng.version>7.12.0</testng.version>

        <checkstyle.configLocation>${project.basedir}/resources/checkstyle/checkstyle.xml</checkstyle.configLocation>
        <lombok-maven-plugin.version>1.18.20.0</lombok-maven-plugin.version>
    </properties>


    <repositories>
        <repository>
            <id>shibboleth-releases</id>
            <url>https://build.shibboleth.net/maven/releases</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>shibboleth-snapshots</id>
            <url>https://build.shibboleth.net/maven/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
        <repository>
            <id>jboss</id>
            <url>https://repository.jboss.org</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>

    <dependencies>
        <!-- Compile Dependencies -->

        <!-- Provided Dependencies -->

        <!-- Runtime Dependencies -->

        <!-- Test Dependencies -->

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>${slf4j.groupId}</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Managed Dependencies -->
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- Esup Otp client dependency -->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>esup-otp-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!--dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>esup-otp-impl</artifactId>
                <version>${project.version}</version>
            </dependency-->

            <!-- IdP BOM when importing IdP dependencies -->
            <dependency>
                <groupId>net.shibboleth.idp</groupId>
                <artifactId>idp-bom</artifactId>
                <version>${idp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-profile-bom</artifactId>
                <version>${shib-profile.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-attribute-bom</artifactId>
                <version>${idp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.opensaml</groupId>
                <artifactId>opensaml-bom</artifactId>
                <version>${opensaml.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.shibboleth</groupId>
                <artifactId>shib-shared-bom</artifactId>
                <version>${shib-shared.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency-->

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <modules>
        <module>esup-otp-api</module>
        <module>esup-otp-impl</module>
        <!-- All DIST modules must come after the -api and -impl modules -->
        <module>esup-otp-dist</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>net.shibboleth.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <links combine.children="append">
                        <link>
                            ${javadoc.url}/java-shib-profile/${shib-profile.version}</link>
                        <link>
                            ${javadoc.url}/java-identity-provider/${idp.version}</link>
                    </links>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifestEntries>
                            <Automatic-Module-Name>${automatic.module.name}</Automatic-Module-Name>
                            <Implementation-Title>${project.artifactId}</Implementation-Title>
                            <Implementation-Version>${project.version}</Implementation-Version>
                            <Sealed>true</Sealed>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <organization>
        <name>RENATER</name>
        <url>https://www.renater.fr</url>
    </organization>
    
</project>
