<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.renater.shibboleth.esup.otp</groupId>
        <artifactId>idp-plugin-esup-otp</artifactId>
        <version>1.1.0-SNAPSHOT</version>
    </parent>

    <name>Shibboleth IdP :: Plugins :: Esup-Otp Login Flow API</name>
    <description>Esup-Otp plugin api.</description>
    <artifactId>esup-otp-api</artifactId>
    <packaging>jar</packaging>

    <properties>
        <checkstyle.configLocation>${project.basedir}/../resources/checkstyle/checkstyle.xml</checkstyle.configLocation>
        <automatic.module.name>fr.renater.shibboleth.esup.otp.api</automatic.module.name>
    </properties>

    <dependencies>
        <!-- Compile Dependencies -->

        <!-- Provided Dependencies -->
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-authn-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-support</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${httpclient.httpcore.groupId}</groupId>
            <artifactId>${httpclient.httpcore.artifactId}</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Runtime Dependencies -->

        <!-- Test dependencies -->
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-testing</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Managed Dependencies -->
    </dependencies>

</project>
