<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.renater.shibboleth.esup.otp</groupId>
        <artifactId>idp-plugin-esup-otp</artifactId>
        <version>1.1.0-SNAPSHOT</version>
        <!--relativePath>../pom.xml</relativePath-->
    </parent>

    <name>Shibboleth IdP :: Plugins :: Esup-Otp Login Flow Impl</name>
    <description>Esup-Otp plugin implementation.</description>
    <artifactId>esup-otp-impl</artifactId>
    <packaging>jar</packaging>

    <properties>
        <checkstyle.configLocation>${project.basedir}/../resources/checkstyle/checkstyle.xml</checkstyle.configLocation>
        <automatic.module.name>fr.renater.shibboleth.idp.plugin.authn.esup.otp.impl</automatic.module.name>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
    </properties>

    <dependencies>
        <!-- Compile Dependencies -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>esup-otp-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>

        <!-- Provided dependencies -->
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-admin-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Needed to allow module/plugin derivation. -->
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-admin-impl</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-authn-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-cli</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.opensaml</groupId>
            <artifactId>opensaml-messaging-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.opensaml</groupId>
            <artifactId>opensaml-profile-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-cli</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-service</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-support</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-attribute-resolver-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>${slf4j.groupId}</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${spring-webflow.groupId}</groupId>
            <artifactId>spring-webflow</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Runtime Dependencies -->

        <!-- Test Dependencies -->
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-authn-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth.idp</groupId>
            <artifactId>idp-testing</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-attribute-resolver-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-attribute-testing</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Needed for XMLObject providers. -->
        <dependency>
            <groupId>org.opensaml</groupId>
            <artifactId>opensaml-core-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.opensaml</groupId>
            <artifactId>opensaml-testing</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>net.shibboleth</groupId>
            <artifactId>shib-testing</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>${spring.groupId}</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Managed Dependencies -->

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.target.directory}</outputDirectory>
                            <includeScope>runtime</includeScope>
                            <excludeTransitive>true</excludeTransitive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestSections>
                            <manifestSection>
                                <name>fr/renater/shibboleth/idp/plugin/authn/esup/otp/</name>
                                <manifestEntries>
                                    <Implementation-Title>${project.artifactId}</Implementation-Title>
                                    <Implementation-Version>${project.version}</Implementation-Version>
                                    <Implementation-Vendor>renater.fr</Implementation-Vendor>
                                </manifestEntries>
                            </manifestSection>
                        </manifestSections>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
