<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.renater.shibboleth.esup.otp</groupId>
        <artifactId>idp-plugin-esup-otp</artifactId>
        <version>1.1.0</version>
    </parent>

    <name>Shibboleth IdP :: Plugins :: Esup-Otp Login Flow Distribution</name>
    <description>Esup-Otp plugin packaging.</description>
    <artifactId>esup-otp-dist</artifactId>
    <packaging>pom</packaging>

    <properties>
        <dist.plugin.finalName>idp-plugin-esup-otp-${project.version}</dist.plugin.finalName>
        <dist.assemblyDirectory>${project.build.directory}/${dist.plugin.finalName}</dist.assemblyDirectory>
        <checkstyle.configLocation>${project.basedir}/../resources/checkstyle/checkstyle.xml</checkstyle.configLocation>
    </properties>

    <build>
        <finalName>${dist.plugin.finalName}</finalName>
        <plugins>
            <!-- Copy src/main/resources to assembly directory. -->
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <includeEmptyDirs>true</includeEmptyDirs>
                            <outputDirectory>${dist.assemblyDirectory}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/src/main/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Assemble -->
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptors>
                        <descriptor>src/main/assembly/assembly.xml</descriptor>
                    </descriptors>
                    <overrideUid>1000</overrideUid>
                    <overrideGid>1000</overrideGid>
                    <tarLongFileMode>gnu</tarLongFileMode>
                </configuration>
            </plugin>
        </plugins>

    </build>

</project>
